services:
  api:
    command: server --host=0.0.0.0
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      VT_DATA_PATH: /data
      VT_DB_CONNECTION_STRING: mongodb://mongo:27017,mongo2:27017,mongo3:27017/virtool?replicaSet=rsmongo
      VT_DEV: "true"
      VT_POSTGRES_CONNECTION_STRING: postgresql+asyncpg://virtool:virtool@postgres/virtool
      VT_REDIS_CONNECTION_STRING: redis://redis:6379
    image: virtool/virtool:7.2.2
    ports:
      - 9950:9950
    profiles:
      - ui
    volumes:
      - source: /home/igboyes/Projects/compose/data
        target: /data
        type: bind
  build-index:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_build_index
    entrypoint: workflow
    image: virtool/build-index:3.0.1
    restart: always
    profiles:
      - backend
      - ui
  create-sample:
    command: --redis-connection-string="redis://redis:6379" --jobs-api-connection-string="http://jobs-api:9990" --redis-list-name jobs_create_sample
    entrypoint: run-workflow
    image: virtool/create-sample:2.1.2
    restart: always
    profiles:
      - backend
      - ui
  create-subtraction:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_create_subtraction
    entrypoint: workflow
    image: virtool/create-subtraction:3.0.1
    restart: always
    profiles:
      - backend
      - ui
  nuvs:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_nuvs
    entrypoint: workflow
    environment:
      VT_RUN_FROM_REDIS_PROC: "6"
      VT_RUN_FROM_REDIS_MEM: "12"
    image: virtool/nuvs:3.0.2
    restart: always
    profiles:
      - backend
      - ui
  pathoscope:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_pathoscope_bowtie
    entrypoint: workflow
    environment:
      VT_RUN_FROM_REDIS_MEM: 8
      VT_RUN_FROM_REDIS_PROC: 8
    image: virtool/pathoscope:2.0.12
    restart: always
    profiles:
      - backend
      - ui
  jobs-api:
    command: jobsAPI --host=0.0.0.0 --port=9990
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      VT_DATA_PATH: /data
      VT_DB_CONNECTION_STRING: mongodb://mongo:27017/virtool
      VT_POSTGRES_CONNECTION_STRING: postgresql+asyncpg://virtool:virtool@postgres/virtool
      VT_REDIS_CONNECTION_STRING: redis://redis:6379
    image: virtool/virtool:7.2.2
    ports:
      - 9990:9990
    volumes:
      - source: /home/igboyes/Projects/compose/data
        target: /data
        type: bind
    profiles:
      - backend
      - ui
  migration:
    environment:
      SQLALCHEMY_URL: postgresql://virtool:virtool@postgres/virtool
    image: virtool/migration:1.0.4
    profiles:
      - backend
      - ui
  mongo:
    image: bitnami/mongodb:4.4
    environment:
      MONGODB_REPLICATE_SET_MODE: primary
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data
    profiles:
      - test
      - backend
      - ui
  postgres:
    environment:
      POSTGRES_PASSWORD: virtool
      POSTGRES_USER: virtool
    image: postgres:13.1
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    profiles:
      - test
      - backend
      - ui
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    profiles:
      - test
      - backend
      - ui
  ui:
    environment:
      VT_UI_API_URL: http://host.docker.internal:9950
      VT_UI_HOST: 0.0.0.0
      VT_UI_PORT: 9900
      VT_UI_USE_PROXY: "true"
    extra_hosts:
      - host.docker.internal:host-gateway
    image: virtool/ui:2.13.6
    ports:
      - 9900:9900
    profiles:
      - backend
version: "3.1"
volumes:
  mongo_data: null
  postgres_data: null
  redis_data: null
