services:
  api:
    command: server --host=0.0.0.0
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      VT_DATA_PATH: /data
      VT_DB_CONNECTION_STRING: mongodb://mongo:27017
      VT_DEV: "true"
      VT_POSTGRES_CONNECTION_STRING: postgresql+asyncpg://virtool:virtool@postgres/virtool
      VT_REDIS_CONNECTION_STRING: redis://redis:6379
    image: virtool/virtool:6.7.1
    ports:
      - 9950:9950
    profiles:
      - ui
    volumes:
      - source: /home/igboyes/Projects/compose/data
        target: /data
        type: bind
  build-index:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_build_index
    entrypoint: workflow
    image: virtool/build-index:3.0.1

    restart: always
  create-sample:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_create_sample
    entrypoint: workflow
    image: virtool/create-sample:2.1.2
    restart: always
  create-subtraction:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_create_subtraction
    entrypoint: workflow
    image: virtool/create-subtraction:3.0.1
    restart: always
  nuvs:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_nuvs
    entrypoint: workflow
    environment:
      VT_RUN_FROM_REDIS_PROC: "6"
      VT_RUN_FROM_REDIS_MEM: "12"
    image: nuvs:test-1
    # image: virtool/nuvs:3.0.0
    restart: always
  pathoscope:
    command: run-from-redis --redis-url="redis://redis:6379" --jobs-api-url="http://jobs-api:9990" --dev-mode --is-analysis-workflow jobs_pathoscope_bowtie
    entrypoint: workflow
    image: virtool/pathoscope:2.0.12
    restart: always
  jobs-api:
    command: jobsAPI --host=0.0.0.0 --port=9990
    depends_on:
      - mongo
      - redis
      - postgres
    environment:
      VT_DATA_PATH: /data
      VT_DB_CONNECTION_STRING: mongodb://mongo:27017
      VT_POSTGRES_CONNECTION_STRING: postgresql+asyncpg://virtool:virtool@postgres/virtool
      VT_REDIS_CONNECTION_STRING: redis://redis:6379
    image: virtool/virtool:6.7.5
    ports:
      - 9990:9990
    volumes:
      - source: /home/igboyes/Projects/compose/data
        target: /data
        type: bind
  migration:
    environment:
      SQLALCHEMY_URL: postgresql://virtool:virtool@postgres/virtool
    image: virtool/migration:1.0.4
  mongo:
    image: mongo:4.4
    ports:
      - 27017:27017
    volumes:
      - vt_mongo_data:/data/db
  postgres:
    environment:
      POSTGRES_PASSWORD: virtool
      POSTGRES_USER: virtool
    image: postgres:13.1
    ports:
      - 5432:5432
    restart: always
    volumes:
      - vt_postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6.0
    ports:
      - 6379:6379
    volumes:
      - vt_redis_data:/data
  typesense:
    image: typesense/typesense:0.22.1
    environment:
      TYPESENSE_API_KEY: virtool
      TYPESENSE_DATA_DIR: /data
    ports:
      - 8108:8108
  ui:
    environment:
      VT_UI_API_URL: http://host.docker.internal:9950
      VT_UI_HOST: 0.0.0.0
      VT_UI_PORT: 9900
      VT_UI_USE_PROXY: "true"
    extra_hosts:
      - host.docker.internal:host-gateway
    image: virtool/ui:2.12.0
    ports:
      - 9900:9900
    profiles:
      - backend
version: "3.1"
volumes:
  vt_mongo_data: null
  vt_postgres_data: null
  vt_redis_data: null
  vt_typesense_data: null
